### ISSUE TITLE
Timing Helper should avoid introducing unnecessary irregular rhythms (or abrupt changes of bpm)

### ISSUE THREAD

**Issue by ciiii0001** [OliBomby/Mapping_Tools#107]
![prob](https://user-images.githubusercontent.com/66686071/88840580-48721580-d20f-11ea-85dc-f9386944b06d.PNG)
This picture shows the problem.
The bookmarks here have roughly same spacing with minor variations, so the first three timing points here should do the same (having roughly same bpm with minor variations)
However, the third timing point having a way higher bpm than the first two, which is weird and doesn't fit the rhythm here (it makes the interval between last two bookmarks a 3/4 gap, while all other gaps between adjacent bookmarks are 1/2). It doesn't help to save red lines either, since there's another red line at the last bookmark in the picture.
(I didn't check the source code but I guess Timing Helper did this because it makes bpm value an integer (or more "human-like"), but imo it shouldn't go beyond the rationality of rhythm)

**Comment by OliBomby** [comment]
Timing Helper uses the timing already present in the map before you run the tool to estimate the number of beats in between every marker (in your case bookmarks). It just takes the closest multiple of the given snap divisors and sometimes this results in an unwanted number of beats (in your case 3/4 instead of 1/2). Whenever I encounter this problem with the tool I always just change the bpm, so it has roughly the right number of beats between markers and then run Timing Helper again.

There is no clear algorithmic way to determine what is a 'logical' number of beats between markers, so this is not an easy problem to fix.

**Comment by OliBomby** [comment]
I'm gonna close this issue, since I dont see me adding any big AI improvement to Timing Helper anytime soon. There were some bugs I fixed, idk maybe that helped.
