### ISSUE TITLE
Feature Request: Hold point for sliderator

### ISSUE THREAD

**Issue by AG89** [OliBomby/Mapping_Tools#157]
Adding something like this would be very useful to me as It's something I noticed wasn't in the program that was avalible. 

Example:
![image](https://user-images.githubusercontent.com/22873716/129649952-ae85fdbb-4628-426f-ae89-0e57dc51dd28.png)

**Comment by OliBomby** [comment]
The reason I didn't add this in is because of its infinite slope. The Sliderator graph likes to restrict the maximum slope to the SV limit so the movement of the slider is actually possible. To implement this kind of interpolation it would need to change its slope depending on the SV limit you put in which is not impossible but annoying. 

You can also recreate the same effect by making linear segments and sliding the second anchor horizontally by holding Shift.
